### ISSUE TITLE
Improvise README.md

### ISSUE THREAD

**Issue by rajayush012** [rajayush012/sahitya#12]
Add all the starter guide.

**Comment by anacarolinaarellano** [comment]
Can I work this issue?

**Comment by rajayush012** [comment]
Sure @anacarolinaarellano 
Let me assign it to you.

**Comment by adeleke5140** [comment]
Hello, I'd like to help out with this issue. what exactly would you like to see changed?

**Comment by anacarolinaarellano** [comment]
> Sure @anacarolinaarellano
> Let me assign it to you.

If you liked my PR, could you add the "hacktoberfest-accepted" label to it?

**Comment by rajayush012** [comment]
Sure
