### ISSUE TITLE
Implement a secure authentication

### ISSUE THREAD

**Issue by rajayush012** [rajayush012/sahitya#14]
Currently, after login, there's an alert that says: 'localhost:3000' has exposed your password.
Make it secure.

**Comment by gitrahulgit** [comment]
I would like to work on it :)

**Comment by rajayush012** [comment]
Go ahead @gitrahulgit 

## Guidelines:
1. Fork the repo.
2. Create a branch
3. Implement the changes and commit them
4. Raise a pull request with the issue number in comment. (Attach screenshots with your PR)

**Comment by rajayush012** [comment]
Auth implemented
