### ISSUE TITLE
Add Mongo Atlas account creation process and key.js in README.md

### ISSUE THREAD

**Issue by rajayush012** [rajayush012/sahitya#19]
In the readme, add how to create Mongo Atlas Account for MongoURI generation.
Also, one has to create '**keys.js**' be in root folder with the content:

```
module.exports = {
    mongoURI: "<your-mongo-uri>",
 };
```
So, add this step too.

**Comment by savanipoojan78** [comment]
could this assign to me

**Comment by rajayush012** [comment]
Go ahead @savanipoojan78 

>Read the contributing guidelines before making raising your PR
